name 'mdsystems-monitoring'
version '0.1.0'
source 'git@github.com:md-systems/puppet-monitoring.git'
author 'MD Systems'
summary 'Setting up a centralized monitoring'
description 'Centralized monitoring using Munin and Icinga.'
project_page 'https://github.com/md-systems/puppet-monitoring'

dependency 'proletaryo/munin', '~> 0.5.0'
dependency 'fsalum/redis', '~> 0.0.11'
dependency 'puppetlabs/rabbitmq', '~>3.1.0'
dependency 'sensu/sensu', '~> 1.0.0'
